<div class="row justify-content-md-center">
    @include('elements.homepage.carroceria', ['nome'=> 'bmw', 'imageUrl'=> asset('images/marcas/bmw.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'chevrolet', 'imageUrl'=> asset('images/marcas/chevrolet.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'citroen', 'imageUrl'=> asset('images/marcas/citroen.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'fiat', 'imageUrl'=> asset('images/marcas/fiat.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'ford', 'imageUrl'=> asset('images/marcas/ford.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'honda', 'imageUrl'=> asset('images/marcas/honda.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'mercedes', 'imageUrl'=> asset('images/marcas/mercedes.jpg')])
    @include('elements.homepage.carroceria', ['nome'=> 'mitsubshi', 'imageUrl'=> asset('images/marcas/mitsubishi.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'nissan', 'imageUrl'=> asset('images/marcas/nissan.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'peugeot', 'imageUrl'=> asset('images/marcas/peugeot.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'renault', 'imageUrl'=> asset('images/marcas/renault.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'toyota', 'imageUrl'=> asset('images/marcas/toyota.png')])
    @include('elements.homepage.carroceria', ['nome'=> 'volvo', 'imageUrl'=> asset('images/marcas/volvo.jpg')])
    @include('elements.homepage.carroceria', ['nome'=> 'vw', 'imageUrl'=> asset('images/marcas/vw.png')])
</div>
